name: latonya.harber
description: Operative
version: 0.0.1
author: ivmebvlm.labo19sx@wr2hulhj.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: latonyaharber
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2025-12-05 20:56:01'
pipelines:
  pipelines/Trent_OberbrunnerJuan_Morefore_DeRhodeMorgan_Mraz:
    name: Trent_OberbrunnerJuan_Morefore_DeRhodeMorgan_Mraz
    description: null
    author: ivmebvlm.labo19sx@wr2hulhj.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-12-05 20:56:01'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-12-05 20:56:01'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-12-05T20:56:01.127506Z'
  name: plibMaven
  version: 8.16.0-SNAPSHOT
  id: '1557503676'
  createdAt: '2025-12-05T20:56:01.127506Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
